Cuisine grouping by geography

In [2]:
import pandas as pd
from copy import deepcopy

dataset_in = "../data/processed/double_cleaned_recipes.json"
dataset_out = "../meal_recommender/data/recipes_group_preprocessed.json"

df = pd.read_json(dataset_in)

# make a copy
df = df.copy()

def add_grouped_tags(tag_list, mapping):

   # Converts  list detailed tags into grouped tags

    if not isinstance(tag_list, list):
        return []

    grouped = []

    for tag in tag_list:
        group = mapping.get(tag)

        if group is not None and group not in grouped:
            grouped.append(group)

    return grouped


# Cuisine mapping

cuisine_mapping = {

    # African

    "African": "African",
    "East African": "African",
    "Ethiopian": "African",
    "Egyptian": "African",
    "Moroccan": "African",
    "North African": "African",
    "South African": "African",
    "Tunisian": "African",
    "West African": "African",

    # American

    "American": "American",
    "California Cuisine": "American",
    "Cajun & Creole": "American",
    "Canadian": "American",
    "Chinese-American": "American",
    "Hawaiian": "American",
    "Italian American": "American",
    "Low Country Cuisine": "American",
    "New England": "American",
    "Soul Food": "American",
    "Southern": "American",
    "Southwestern": "American",
    "Tex-Mex": "American",


    # Asian

    "Asian": "Asian",
    "Bangladeshi": "Asian",
    "Burmese": "Asian",
    "Cantonese": "Asian",
    "Chinese": "Asian",
    "East Asian": "Asian",
    "Filipino": "Asian",
    "Indian": "Asian",
    "Indonesian": "Asian",
    "Japanese": "Asian",
    "Korean": "Asian",
    "Laotian": "Asian",
    "Pakistani": "Asian",
    "Sichuanese": "Asian",
    "South Asian": "Asian",
    "Southeast Asian": "Asian",
    "Sri Lankan": "Asian",
    "Taiwanese": "Asian",
    "Thai": "Asian",
    "Vietnamese": "Asian",


    # Caribbean

    "Caribbean": "Caribbean",
    "Cuban": "Caribbean",
    "Dominican": "Caribbean",
    "Jamaican": "Caribbean",
    "Puerto Rican": "Caribbean",
    "Trinidadian": "Caribbean",

   
    # European
 
    "Austrian": "European",
    "Basque": "European",
    "British": "European",
    "Danish": "European",
    "Eastern European": "European",
    "European": "European",
    "French": "European",
    "Georgian": "European",
    "German": "European",
    "Irish": "European",
    "Italian": "European",
    "Norwegian": "European",
    "Polish": "European",
    "Portuguese": "European",
    "Russian": "European",
    "Scandinavian": "European",
    "Sicilian": "European",
    "Spanish": "European",
    "Swedish": "European",

  
    # Latin American

    "Argentinean": "Latin American",
    "Brazilian": "Latin American",
    "Central American": "Latin American",
    "Colombian": "Latin American",
    "Latin American": "Latin American",
    "Mexican": "Latin American",
    "Oaxacan": "Latin American",
    "Peruvian": "Latin American",
    "South American": "Latin American",
    "Venezuelan": "Latin American",


    # Mediterranean

    "Greek": "Mediterranean",
    "Mediterranean": "Mediterranean",

   
    # Middle Eastern
   
    "Armenian": "Middle Eastern",
    "Iranian": "Middle Eastern",
    "Israeli": "Middle Eastern",
    "Jewish": "Middle Eastern",
    "Lebanese": "Middle Eastern",
    "Levantine": "Middle Eastern",
    "Middle Eastern": "Middle Eastern",
    "Palestinian": "Middle Eastern",
    "Persian": "Middle Eastern",
    "Turkish": "Middle Eastern",
    "Yemeni": "Middle Eastern",
}


# Add grouped cuisine tags


def preprocess_cuisine(tags):

    tags = deepcopy(tags)

    cuisines = tags.get("cuisine", [])

    tags["cuisine_grouped"] = add_grouped_tags(
        cuisines,
        cuisine_mapping
    )

    return tags


df["tags"] = df["tags"].apply(preprocess_cuisine)

print("cuisine_grouped added.")

# Quick sanity check
print(df[["title", "tags"]].head())

cuisine_grouped added.
                                           title  \
0  Penne with Shrimp, Red Onion, and Goat Cheese
1               Fiorentini with Butternut Squash
2                             Apple Noodle Kugel
3                            Mushroom Stroganoff
4                        Fridge-Dive Pesto Pasta

                                                tags
0  {'type': ['Pasta', 'Penne'], 'cuisine': ['Ital...
1  {'type': ['Pasta'], 'cuisine': ['Italian', 'Eu...
2  {'type': ['Egg Noodle', 'Noodle', 'Pasta & Noo...
3  {'type': ['Pasta', 'Egg Noodle', 'Noodle', 'Pa...
4  {'type': ['Pasta', 'Fusilli'], 'cuisine': ['It...

In [3]:
preview = pd.DataFrame({
    "title": df["title"],
    "cuisine": df["tags"].apply(lambda x: x.get("cuisine", [])),
    "cuisine_grouped": df["tags"].apply(lambda x: x.get("cuisine_grouped", []))
})

preview.head(100)

,title,cuisine,cuisine_grouped
0,"Penne with Shrimp, Red Onion, and Goat Cheese","[Italian American, Italian, European]","[American, European]"
1,Fiorentini with Butternut Squash,"[Italian, European]",[European]
2,Apple Noodle Kugel,[Jewish],[Middle Eastern]
3,Mushroom Stroganoff,"[Eastern European, European]",[European]
4,Fridge-Dive Pesto Pasta,"[Italian, European]",[European]
...,...,...,...
95,The Silkiest Carbonara,"[Italian, European]",[European]
96,Potato Salad,"[Southern, American]",[American]
97,Rice-Studded Meatballs,"[Asian, Chinese, East Asian]",[Asian]
98,Fettuccine With Sausage and Kale,"[Italian, European]",[European]
99,Radicchio and Citrus Salad with Burrata,"[Italian, European]",[European]

Grouping by ingredients:

In [4]:
ingredient_mapping = {


    # Fruit

    "Apple": "Fruit",
    "Apricot": "Fruit",
    "Avocado": "Fruit",
    "Banana": "Fruit",
    "Berry": "Fruit",
    "Blood Orange": "Fruit",
    "Cantaloupe": "Fruit",
    "Cherry": "Fruit",
    "Citrus": "Fruit",
    "Clementine": "Fruit",
    "Coconut": "Fruit",
    "Cranberry": "Fruit",
    "Date": "Fruit",
    "Dried Apricot": "Fruit",
    "Dried Cherry": "Fruit",
    "Dried Cranberry": "Fruit",
    "Dried Currant": "Fruit",
    "Dried Fruit": "Fruit",
    "Fig": "Fruit",
    "Fruit": "Fruit",
    "Grape": "Fruit",
    "Grapefruit": "Fruit",
    "Kumquat": "Fruit",
    "Lemon": "Fruit",
    "Meyer Lemon": "Fruit",
    "Lime": "Fruit",
    "Mango": "Fruit",
    "Melon": "Fruit",
    "Orange": "Fruit",
    "Papaya": "Fruit",
    "Peach": "Fruit",
    "Pear": "Fruit",
    "Pineapple": "Fruit",
    "Plantain": "Fruit",
    "Plum": "Fruit",
    "Pomegranate": "Fruit",
    "Prune": "Fruit",
    "Raisin": "Fruit",
    "Stone Fruit": "Fruit",
    "Tamarind": "Fruit",
    "Tangerine": "Fruit",
    "Watermelon": "Fruit",

  
    # Vegetables

    "Artichoke": "Vegetables",
    "Arugula": "Vegetables",
    "Asparagus": "Vegetables",
    "Beet": "Vegetables",
    "Bell Pepper": "Vegetables",
    "Bok Choy": "Vegetables",
    "Broccoli Rabe": "Vegetables",
    "Broccoli/Broccolini": "Vegetables",
    "Brussels Sprout": "Vegetables",
    "Butternut Squash": "Vegetables",
    "Cabbage": "Vegetables",
    "Canned Tomato": "Vegetables",
    "Carrot": "Vegetables",
    "Cauliflower": "Vegetables",
    "Celery": "Vegetables",
    "Celery Root": "Vegetables",
    "Chicory": "Vegetables",
    "Chinese Long Bean": "Vegetables",
    "Collard Greens": "Vegetables",
    "Corn": "Vegetables",
    "Cucumber": "Vegetables",
    "Daikon": "Vegetables",
    "Dandelion Greens": "Vegetables",
    "Eggplant": "Vegetables",
    "Endive": "Vegetables",
    "Escarole": "Vegetables",
    "Fennel": "Vegetables",
    "Frisée": "Vegetables",
    "Garlic": "Vegetables",
    "Ginger": "Vegetables",
    "Green Bean": "Vegetables",
    "Green Cabbage": "Vegetables",
    "Hearts of Palm": "Vegetables",
    "Heirloom Tomato": "Vegetables",
    "Horseradish": "Vegetables",
    "Iceberg Lettuce": "Vegetables",
    "Jerusalem Artichoke": "Vegetables",
    "Jicama": "Vegetables",
    "Kabocha Squash": "Vegetables",
    "Kale": "Vegetables",
    "Leafy Greens": "Vegetables",
    "Leek": "Vegetables",
    "Lettuce": "Vegetables",
    "Mizuna": "Vegetables",
    "Mustard Greens": "Vegetables",
    "Napa Cabbage": "Vegetables",
    "Okra": "Vegetables",
    "Olive": "Vegetables",
    "Onion": "Vegetables",
    "Parsnip": "Vegetables",
    "Pea Shoot": "Vegetables",
    "Pearl Onion": "Vegetables",
    "Potato": "Vegetables",
    "Pumpkin": "Vegetables",
    "Radicchio": "Vegetables",
    "Radish": "Vegetables",
    "Ramps": "Vegetables",
    "Red Cabbage": "Vegetables",
    "Red Onion": "Vegetables",
    "Romaine": "Vegetables",
    "Romanesco": "Vegetables",
    "Root Vegetable": "Vegetables",
    "Rutabaga": "Vegetables",
    "Savoy Cabbage": "Vegetables",
    "Scallion": "Vegetables",
    "Shallot": "Vegetables",
    "Spinach": "Vegetables",
    "Spring Onion": "Vegetables",
    "Sprout": "Vegetables",
    "Squash": "Vegetables",
    "Sugar Snap Pea": "Vegetables",
    "Summer Squash": "Vegetables",
    "Sun-Dried Tomato": "Vegetables",
    "Sweet Potato": "Vegetables",
    "Swiss Chard": "Vegetables",
    "Tomatillo": "Vegetables",
    "Tomato": "Vegetables",
    "Cherry Tomato": "Vegetables",
    "Grape Tomato": "Vegetables",
    "Plum Tomato": "Vegetables",
    "Turnip": "Vegetables",
    "Vegetable": "Vegetables",
    "Watercress": "Vegetables",
    "Yukon Gold Potato": "Vegetables",
    "Red Skin Potato": "Vegetables",
    "Russet Potato": "Vegetables",
    "Fingerling Potato": "Vegetables",
    "Zucchini": "Vegetables",

  
    # Beans & Legumes
   
    "Bean and Legume": "Beans & Legumes",
    "Black Bean": "Beans & Legumes",
    "Black-Eyed Pea": "Beans & Legumes",
    "Cannellini Bean": "Beans & Legumes",
    "Chickpea": "Beans & Legumes",
    "Edamame": "Beans & Legumes",
    "Fava Bean": "Beans & Legumes",
    "French Lentil": "Beans & Legumes",
    "Green Lentil": "Beans & Legumes",
    "Brown Lentil": "Beans & Legumes",
    "Black Lentil": "Beans & Legumes",
    "Red Lentil": "Beans & Legumes",
    "Lentil": "Beans & Legumes",
    "Kidney Bean": "Beans & Legumes",
    "Lima Bean": "Beans & Legumes",
    "Navy Bean": "Beans & Legumes",
    "Pea": "Beans & Legumes",
    "Pinto Bean": "Beans & Legumes",
    "White Bean": "Beans & Legumes",

 
    # Mushrooms
  
    "Mushroom": "Mushrooms",
    "Button Mushroom": "Mushrooms",
    "Crimini Mushroom": "Mushrooms",
    "Chanterelle Mushroom": "Mushrooms",
    "Enoki Mushroom": "Mushrooms",
    "Maitake Mushroom": "Mushrooms",
    "Oyster Mushroom": "Mushrooms",
    "Porcini Mushroom": "Mushrooms",
    "Shiitake Mushroom": "Mushrooms",

    # Red Meat
    "Beef": "Red Meat",
    "Beef Chuck": "Red Meat",
    "Beef Rib": "Red Meat",
    "Beef Tenderloin": "Red Meat",
    "Brisket": "Red Meat",
    "Ground Beef": "Red Meat",
    "Rib Eye Steak": "Red Meat",
    "Short Rib": "Red Meat",
    "Steak": "Red Meat",
    "Veal": "Red Meat",
    "Bison": "Red Meat",
    "Lamb": "Red Meat",
    "Lamb Chop": "Red Meat",
    "Lamb Shank": "Red Meat",
    "Lamb Shoulder": "Red Meat",
    "Ground Lamb": "Red Meat",
    "Rabbit": "Red Meat",
    "Liver": "Red Meat",
    "Meat": "Red Meat",

    # Pork
    "Bacon": "Pork",
    "Baby Back Rib": "Pork",
    "Chorizo": "Pork",
    "Corned Beef": "Pork",
    "Cured Meat": "Pork",
    "Guanciale": "Pork",
    "Ham": "Pork",
    "Kielbasa": "Pork",
    "Pancetta": "Pork",
    "Pork": "Pork",
    "Pork Belly": "Pork",
    "Pork Chop": "Pork",
    "Pork Loin": "Pork",
    "Pork Rib": "Pork",
    "Pork Shoulder": "Pork",
    "Pork Tenderloin": "Pork",
    "Prosciutto": "Pork",
    "Salami": "Pork",
    "Sausage": "Pork",
    "Soppressata": "Pork",
    "Spare Rib": "Pork",
    "Ground Pork": "Pork",

    # Poultry
    "Chicken": "Poultry",
    "Chicken Breast": "Poultry",
    "Chicken Drumstick": "Poultry",
    "Chicken Leg": "Poultry",
    "Chicken Thigh": "Poultry",
    "Chicken Wing": "Poultry",
    "Whole Chicken": "Poultry",
    "Cornish Hen": "Poultry",
    "Duck": "Poultry",
    "Ground Chicken": "Poultry",
    "Turkey": "Poultry",
    "Ground Turkey": "Poultry",
    "Poultry": "Poultry",

    # Fish
    "Anchovy": "Fish",
    "Arctic Char": "Fish",
    "Bass": "Fish",
    "Black Bass": "Fish",
    "Black Cod": "Fish",
    "Branzino": "Fish",
    "Catfish": "Fish",
    "Cod": "Fish",
    "Fish": "Fish",
    "Flounder": "Fish",
    "Haddock": "Fish",
    "Halibut": "Fish",
    "Mackerel": "Fish",
    "Mahi-Mahi": "Fish",
    "Salmon": "Fish",
    "Sardine": "Fish",
    "Sea Bass": "Fish",
    "Smoked Salmon": "Fish",
    "Smoked Trout": "Fish",
    "Snapper": "Fish",
    "Sole": "Fish",
    "Swordfish": "Fish",
    "Tilapia": "Fish",
    "Trout": "Fish",
    "Tuna": "Fish",

    # Seafood & Shellfish
    "Caviar": "Seafood & Shellfish",
    "Clam": "Seafood & Shellfish",
    "Crab": "Seafood & Shellfish",
    "Lobster": "Seafood & Shellfish",
    "Mussel": "Seafood & Shellfish",
    "Octopus": "Seafood & Shellfish",
    "Oyster": "Seafood & Shellfish",
    "Scallop": "Seafood & Shellfish",
    "Seafood": "Seafood & Shellfish",
    "Shellfish": "Seafood & Shellfish",
    "Shrimp": "Seafood & Shellfish",
    "Squid": "Seafood & Shellfish",


        # Dairy & Cheese
    "Asiago": "Dairy & Cheese",
    "Blue Cheese": "Dairy & Cheese",
    "Burrata": "Dairy & Cheese",
    "Buttermilk": "Dairy & Cheese",
    "Butter": "Dairy & Cheese",
    "Cheddar": "Dairy & Cheese",
    "Cheese": "Dairy & Cheese",
    "Cotija": "Dairy & Cheese",
    "Cream Cheese": "Dairy & Cheese",
    "Dairy": "Dairy & Cheese",
    "Feta": "Dairy & Cheese",
    "Fontina": "Dairy & Cheese",
    "Goat Cheese": "Dairy & Cheese",
    "Gorgonzola": "Dairy & Cheese",
    "Gruyère": "Dairy & Cheese",
    "Halloumi": "Dairy & Cheese",
    "Manchego": "Dairy & Cheese",
    "Mascarpone": "Dairy & Cheese",
    "Monterey Jack": "Dairy & Cheese",
    "Mozzarella": "Dairy & Cheese",
    "Paneer": "Dairy & Cheese",
    "Parmesan": "Dairy & Cheese",
    "Pecorino": "Dairy & Cheese",
    "Provolone": "Dairy & Cheese",
    "Queso Fresco": "Dairy & Cheese",
    "Ricotta": "Dairy & Cheese",
    "Ricotta Salata": "Dairy & Cheese",
    "Sour Cream": "Dairy & Cheese",
    "Swiss Cheese": "Dairy & Cheese",
    "Yogurt": "Dairy & Cheese",

    # Grains & Cereals
    "Amaranth": "Grains & Cereals",
    "Arborio Rice": "Grains & Cereals",
    "Barley": "Grains & Cereals",
    "Basmati Rice": "Grains & Cereals",
    "Brown Rice": "Grains & Cereals",
    "Bulgur": "Grains & Cereals",
    "Farro": "Grains & Cereals",
    "Freekeh": "Grains & Cereals",
    "Grits": "Grains & Cereals",
    "Hominy": "Grains & Cereals",
    "Jasmine Rice": "Grains & Cereals",
    "Masa": "Grains & Cereals",
    "Matzo": "Grains & Cereals",
    "Oat": "Grains & Cereals",
    "Polenta": "Grains & Cereals",
    "Quinoa": "Grains & Cereals",
    "Rice": "Grains & Cereals",
    "Rice & Grains": "Grains & Cereals",
    "Sorghum": "Grains & Cereals",
    "Sushi Rice": "Grains & Cereals",
    "Wheat Berry": "Grains & Cereals",
    "Wild Rice": "Grains & Cereals",

    # Flour & Baking
    "Bread Flour": "Flour & Baking",
    "Chickpea Flour": "Flour & Baking",
    "Cornmeal": "Flour & Baking",
    "Flour": "Flour & Baking",
    "Semolina Flour": "Flour & Baking",
    "Whole Wheat Flour": "Flour & Baking",
    "Wheat Germ": "Flour & Baking",
    "Yeast": "Flour & Baking",

    # Nuts & Seeds
    "Almond": "Nuts & Seeds",
    "Cashew": "Nuts & Seeds",
    "Chestnut": "Nuts & Seeds",
    "Flaxseed": "Nuts & Seeds",
    "Hazelnut": "Nuts & Seeds",
    "Macadamia Nut": "Nuts & Seeds",
    "Nut": "Nuts & Seeds",
    "Peanut": "Nuts & Seeds",
    "Peanut Butter": "Nuts & Seeds",
    "Pecan": "Nuts & Seeds",
    "Pine Nut": "Nuts & Seeds",
    "Pistachio": "Nuts & Seeds",
    "Poppy Seed": "Nuts & Seeds",
    "Pumpkin Seed": "Nuts & Seeds",
    "Seed": "Nuts & Seeds",
    "Tahini": "Nuts & Seeds",
    "Walnut": "Nuts & Seeds",


        # Herbs
    "Basil": "Herbs",
    "Chive": "Herbs",
    "Cilantro": "Herbs",
    "Curry Leaf": "Herbs",
    "Dill": "Herbs",
    "Lemongrass": "Herbs",
    "Marjoram": "Herbs",
    "Mint": "Herbs",
    "Oregano": "Herbs",
    "Parsley": "Herbs",
    "Rosemary": "Herbs",
    "Sage": "Herbs",
    "Tarragon": "Herbs",
    "Thai Basil": "Herbs",
    "Thyme": "Herbs",

    # Spices & Seasonings
    "Aleppo-Style Pepper": "Spices & Seasonings",
    "Cardamom": "Spices & Seasonings",
    "Chocolate": "Spices & Seasonings",
    "Cinnamon": "Spices & Seasonings",
    "Cocoa": "Spices & Seasonings",
    "Galangal": "Spices & Seasonings",
    "Harissa": "Spices & Seasonings",
    "Herbs & Spices": "Spices & Seasonings",
    "Miso": "Spices & Seasonings",
    "Nutmeg": "Spices & Seasonings",
    "Nutritional Yeast": "Spices & Seasonings",
    "Palm Sugar": "Spices & Seasonings",
    "Paprika": "Spices & Seasonings",
    "Saffron": "Spices & Seasonings",
    "Sichuan Peppercorn": "Spices & Seasonings",
    "Sumac": "Spices & Seasonings",
    "Turmeric": "Spices & Seasonings",
    "Vanilla": "Spices & Seasonings",
    "Za'atar": "Spices & Seasonings",

    # Chili Peppers
    "Anaheim Chile": "Chili Peppers",
    "Ancho Chile": "Chili Peppers",
    "Calabrian Chile": "Chili Peppers",
    "Chile": "Chili Peppers",
    "Chile de Árbol": "Chili Peppers",
    "Chipotle": "Chili Peppers",
    "Fresno Chile": "Chili Peppers",
    "Guajillo Chile": "Chili Peppers",
    "Habanero Chile": "Chili Peppers",
    "Jalapeño": "Chili Peppers",
    "New Mexico Chile": "Chili Peppers",
    "Pasilla Chile": "Chili Peppers",
    "Poblano Chile": "Chili Peppers",
    "Scotch Bonnet": "Chili Peppers",
    "Serrano Chile": "Chili Peppers",
    "Thai Chile": "Chili Peppers",

    # Plant Proteins
    "Tofu": "Plant Proteins",
    "Tempeh": "Plant Proteins",

    # Sea Vegetables
    "Kombu": "Sea Vegetables",
    "Nori": "Sea Vegetables",
    "Seaweed": "Sea Vegetables",

    # Oils, Sauces & Condiments
    "Castelvetrano Olive": "Oils, Sauces & Condiments",
    "Coconut Milk": "Oils, Sauces & Condiments",
}

# Add grouped ingredient tags

def preprocess_ingredients(tags):

    tags = deepcopy(tags)

    ingredients = tags.get("ingredient", [])

    tags["ingredient_grouped"] = add_grouped_tags(
        ingredients,
        ingredient_mapping
    )

    return tags


df["tags"] = df["tags"].apply(preprocess_ingredients)

print("✓ ingredient_grouped successfully added.")

preview = pd.DataFrame({
    "title": df["title"],
    "ingredient": df["tags"].apply(lambda x: x.get("ingredient", [])),
    "ingredient_grouped": df["tags"].apply(lambda x: x.get("ingredient_grouped", []))
})

preview.head(10)

✓ ingredient_grouped successfully added.

,title,ingredient,ingredient_grouped
0,"Penne with Shrimp, Red Onion, and Goat Cheese","[Shrimp, Shellfish, Seafood, Cherry Tomato, To...","[Seafood & Shellfish, Vegetables, Dairy & Cheese]"
1,Fiorentini with Butternut Squash,"[Butternut Squash, Squash, Vegetable, Parmesan...","[Vegetables, Dairy & Cheese, Herbs, Spices & S..."
2,Apple Noodle Kugel,"[Sour Cream, Dairy, Raisin, Dried Fruit, Fruit...","[Dairy & Cheese, Fruit]"
3,Mushroom Stroganoff,"[Crimini Mushroom, Mushroom, Vegetable]","[Mushrooms, Vegetables]"
4,Fridge-Dive Pesto Pasta,"[Ricotta Salata, Ricotta, Cheese, Dairy, Leafy...","[Dairy & Cheese, Vegetables]"
5,Polenta With Mushrooms,"[Polenta, Rice & Grains, Porcini Mushroom, Mus...","[Grains & Cereals, Mushrooms, Vegetables]"
6,Salted Plum Steamed Fish,"[Fish, Seafood, Plum, Stone Fruit, Fruit]","[Fish, Seafood & Shellfish, Fruit]"
7,Flammkuchen,[],[]
8,Gorditas con Camarones,"[Shrimp, Shellfish, Seafood, Masa, Rice & Grai...","[Seafood & Shellfish, Grains & Cereals, Chili ..."
9,Beef Sliders with Provolone and Balsamic Onions,"[Ground Beef, Beef, Meat, Provolone, Cheese, D...","[Red Meat, Dairy & Cheese, Vegetables]"

Type grouping

In [5]:
type_mapping = {

    # Pasta & Noodles
    "Bucatini": "Pasta & Noodles",
    "Capellini": "Pasta & Noodles",
    "Ditalini": "Pasta & Noodles",
    "Egg Noodle": "Pasta & Noodles",
    "Farfalle": "Pasta & Noodles",
    "Fettuccine": "Pasta & Noodles",
    "Fregola": "Pasta & Noodles",
    "Fusilli": "Pasta & Noodles",
    "Glass Noodle": "Pasta & Noodles",
    "Gnocchi": "Pasta & Noodles",
    "Linguine": "Pasta & Noodles",
    "Lo Mein Noodle": "Pasta & Noodles",
    "Macaroni": "Pasta & Noodles",
    "Noodle": "Pasta & Noodles",
    "Orecchiette": "Pasta & Noodles",
    "Orzo": "Pasta & Noodles",
    "Pappardelle": "Pasta & Noodles",
    "Pasta": "Pasta & Noodles",
    "Pasta & Noodles": "Pasta & Noodles",
    "Pasta Shells": "Pasta & Noodles",
    "Penne": "Pasta & Noodles",
    "Ramen Noodle": "Pasta & Noodles",
    "Ravioli": "Pasta & Noodles",
    "Rice Noodle": "Pasta & Noodles",
    "Rigatoni": "Pasta & Noodles",
    "Soba Noodle": "Pasta & Noodles",
    "Spaghetti": "Pasta & Noodles",
    "Tagliatelle": "Pasta & Noodles",
    "Udon Noodle": "Pasta & Noodles",
    "Ziti": "Pasta & Noodles",
    "Mac and Cheese": "Pasta & Noodles",

    # Rice & Grain Dishes
    "Couscous": "Rice & Grain Dishes",
    "Fried Rice": "Rice & Grain Dishes",
    "Grain Bowl": "Rice & Grain Dishes",
    "Israeli Couscous": "Rice & Grain Dishes",
    "Paella": "Rice & Grain Dishes",
    "Pilaf": "Rice & Grain Dishes",
    "Porridge": "Rice & Grain Dishes",
    "Rice Bowl": "Rice & Grain Dishes",
    "Risotto": "Rice & Grain Dishes",

    # Soups, Stews & Curries
    "Chili": "Soups, Stews & Curries",
    "Chowder": "Soups, Stews & Curries",
    "Cold Soup": "Soups, Stews & Curries",
    "Curry": "Soups, Stews & Curries",
    "Dal": "Soups, Stews & Curries",
    "Gazpacho": "Soups, Stews & Curries",
    "Gumbo": "Soups, Stews & Curries",
    "Posole": "Soups, Stews & Curries",
    "Soup": "Soups, Stews & Curries",
    "Soup/Stew": "Soups, Stews & Curries",
    "Stew": "Soups, Stews & Curries",

    # Salads
    "Caesar Salad": "Salads",
    "Cole Slaw": "Salads",
    "Crudité": "Salads",
    "Pasta Salad": "Salads",
    "Potato Salad": "Salads",
    "Salad": "Salads",
    "Slaw": "Salads",
    "Tabbouleh": "Salads",

    # Sandwiches & Wraps
    "Burger": "Sandwiches & Wraps",
    "Burrito": "Sandwiches & Wraps",
    "Quesadilla": "Sandwiches & Wraps",
    "Sandwich": "Sandwiches & Wraps",
    "Taco": "Sandwiches & Wraps",
    "Tostada": "Sandwiches & Wraps",
    "Veggie Burger": "Sandwiches & Wraps",
    "Wrap": "Sandwiches & Wraps",

    # Pizza & Bread
    "Bread": "Pizza & Bread",
    "Bruschetta": "Pizza & Bread",
    "Cornbread": "Pizza & Bread",
    "Flatbread": "Pizza & Bread",
    "Pizza": "Pizza & Bread",
    "Rolls": "Pizza & Bread",
    "Toast": "Pizza & Bread",

    # Main Dishes
    "Casserole": "Main Dishes",
    "Cutlet": "Main Dishes",
    "Dumpling": "Main Dishes",
    "Enchilada": "Main Dishes",
    "Fried Chicken": "Main Dishes",
    "Gratin": "Main Dishes",
    "Hash": "Main Dishes",
    "Larb": "Main Dishes",
    "Lasagna": "Main Dishes",
    "Meatball": "Main Dishes",
    "Meatloaf": "Main Dishes",
    "Omelet": "Main Dishes",
    "Ribs": "Main Dishes",
    "Skewer": "Main Dishes",
    "Stir-Fry": "Main Dishes",
    "Stuffing": "Main Dishes",

    # Seafood Dishes
    "Ceviche": "Seafood Dishes",
    "Escabèche": "Seafood Dishes",
    "Sushi": "Seafood Dishes",

    # Breakfast
    "Chilaquiles": "Breakfast",
    "Egg": "Breakfast",
    "Frittata": "Breakfast",
    "Granola": "Breakfast",
    "Oatmeal": "Breakfast",
}


# Add grouped type tags

def preprocess_type(tags):

    tags = deepcopy(tags)

    recipe_types = tags.get("type", [])

    tags["type_grouped"] = add_grouped_tags(
        recipe_types,
        type_mapping
    )

    return tags


df["tags"] = df["tags"].apply(preprocess_type)

print("✓ type_grouped successfully added.")

✓ type_grouped successfully added.

In [6]:
df.to_json(dataset_out, 
                orient='records', 
                indent=2, 
                force_ascii=False)

print("Saved successfully")

Saved successfully